### ISSUE TITLE
Clock line isn't recognized as valid

### ISSUE THREAD

**Issue by Daenyth** [gruppler/PTN-Ninja#16] opened 2016-10-01 14:00 UTC
playtak-generated PTNs have a `[Clock]` section which ptn.ninja says is invalid. An example line is `[Clock "10:0 +15"]` for a game with 10 minutes +15s add

This is especially annoying since the US Tak Open is going on right now and ptn.ninja is really nice to use for sharing games

**Comment by gruppler** [comment] 2016-10-01 17:25
Duplicate of #14.

**Closed by gruppler** 2016-10-01 17:25 UTC
