### ISSUE TITLE
View Notation and Retain Functionality

### ISSUE THREAD

**Issue by Abyssal-Tak** [gruppler/PTN-Ninja#13] opened 2016-09-13 00:18 UTC
I like to always have the game notation open when I study a game, so I can always have my bearings straight, but currently it's impossible to navigate through moves easily when the game notation is open—clicking on each move individually with the cursor is rather cumbersome. Even a simple forward and backward arrow functionality from the notation screen would be fine, but I think it also might be useful to be able to view the notation in a mode where it is not opened in text-editing mode. As I said, I always want to be able to see the notation, but seldom do I want to edit it. Thank you for your consideration.

**Comment by gruppler** [comment] 2016-09-13 00:37
Duplicate of #3

**Closed by gruppler** 2016-09-13 00:37 UTC
